#Seeds for User
User.create(email: "user1@example.com", first_name: "jose", last_name: "costa")
User.create(email: "user2@example.com", first_name: "consuelo", last_name: "lemp")
User.create(email: "user3@example.com", first_name: "andres", last_name: "howard")
User.create(email: "user4@example.com", first_name: "matias", last_name: "recabarren")
User.create(email: "user5@example.com", first_name: "claudio", last_name: "telha")
User.create(email: "user6@example.com", first_name: "enrique", last_name: "saint-pierre")
User.create(email: "user7@example.com", first_name: "milena", last_name: "bonacic")
User.create(email: "user8@example.com", first_name: "pilar", last_name: "gazmuri")
User.create(email: "user9@example.com", first_name: "pamela", last_name: "bustamante")
User.create(email: "user10@example.com", first_name: "daniel", last_name: "escaff")

#Seeds for Post
Post.create(author: "user1@example.com", title: "hola", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet nulla auctor, vestibulum magna sed, convallis ex. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sed odio dui. Donec sed odio dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", published: 1)
Post.create(author: "user1@example.com", title: "universidad", content: "Estoy estudiando en la universidad de los Andes, una de las mejores universidades del país. Me encanta la vida universitaria, hay siempre algo que hacer, alguien con quien hablar, algún lugar al que ir. La universidad es un lugar donde se aprende mucho, no solo en el aula, sino también en la vida diaria.", published: 1)
Post.create(author: "user1@example.com", title: "ingenieria", content: "Estoy estudiando ingeniería civil industrial, una carrera muy demandante, pero también muy gratificante. Me gusta la forma en que se combinan la teoría y la práctica para resolver problemas complejos. La ingeniería es un campo en constante evolución, siempre hay algo nuevo que aprender, algún problema que resolver.", published: 1)
Post.create(author: "user1@example.com", title: "concentracion", content: "Estoy en la concentración de desarrollo web, un campo que me apasiona. Me gusta la forma en que se puede crear algo desde cero, algo que puede ser utilizado por miles de personas. La concentración es un lugar donde se aprende mucho, no solo sobre programación, sino también sobre diseño, usabilidad y experiencia del usuario.", published: 1)
Post.create(author: "user1@example.com", title: "gustos musicales", content: "Me gusta mucho el metal y el rock, géneros que me permiten expresar mis emociones de manera intensa. La música es un parte importante de mi vida, siempre estoy escuchando algo nuevo, descubriendo bandas y artistas que me gustan. La música es un lenguaje universal, puede unir a las personas de manera que nada más puede.", published: 1)
Post.create(author: "user1@example.com", title: "gaming", content: "Me gusta mucho jugar videojuegos, es una forma de relajarme y divertirme. Me gustan juegos de todo tipo, desde juegos de estrategia hasta juegos de acción. La industria de los videojuegos es muy grande y en constante evolución, siempre hay algo nuevo que jugar, algún juego que descubrir.", published: 1)
Post.create(author: "user1@example.com", title: "perros", content: "Tengo 3 perros, Otto, Emma y Chewy, son mis mejores amigos. Me encanta la forma en que siempre están ahí para mí, siempre dispuestos a jugar o simplemente a estar cerca. Los perros son animales increíbles, pueden enseñarnos mucho sobre la lealtad y el amor incondicional.", published: 1)
Post.create(author: "user1@example.com", title: "guitarra", content: "Tengo 6 guitarras, cada una con su propia personalidad y sonido. Me gusta tocar la guitarra, es una forma de expresarme de manera creativa. La guitarra es un instrumento versátil, se puede tocar en muchos estilos diferentes, desde el rock hasta el jazz.", published: 1)
Post.create(author: "user1@example.com", title: "estudiar", content: "A veces estudio mucho, es una forma de mejorar mis habilidades y conocimientos. Me gusta aprender nuevas cosas, descubrir conceptos y teorías que no conocía. El estudio es un proceso continuo, siempre hay algo nuevo que aprender, algún tema que profundizar.", published: 1)
Post.create(author: "user1@example.com", title: "calculo", content: "Me gusta mucho integrar, es una forma de resolver problemas complejos de manera elegante. La integración es un concepto fundamental en el cálculo, permite resolver problemas que de otra manera serían imposibles de resolver. Me gusta la forma en que la integración se puede aplicar a muchos campos diferentes, desde la física hasta
#Seeds for Comment
Comment.create(author: "user1@example.com", content: "hola buenos dias tambien")
Comment.create(author: "user1@example.com", content: "que bueno, yo tambien soy de la uandes")
Comment.create(author: "user1@example.com", content: "wow, yo tambien estudio industrial")
Comment.create(author: "user1@example.com", content: "yo casi quedo en la concentracion de fluid mechanics")
Comment.create(author: "user1@example.com", content: "mis grupos favoritos son Metallica, System of a Down y Megadeth")
Comment.create(author: "user1@example.com", content: "me encantan mis perros, y echo de menos a los que ya no estan, Jaguer y Noah")
Comment.create(author: "user1@example.com", content: "me encantaria tener una Explorer o una Flying V")
Comment.create(author: "user1@example.com", content: "A veces estudio poco")
Comment.create(author: "user1@example.com", content: "pero enseño estadistica asi que ya no integro :(")
Comment.create(author: "user1@example.com", content: "creo que me falto un comentario")